name: CI Checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  e2e-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
    - name: Install dependencies
      run: yarn
    - name: Install browsers for E2E testing
      run: yarn playwright install --with-deps
    - name: Run E2E tests
      run: yarn test:e2e
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  unit-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
    - name: Install dependencies
      run: yarn
    - name: Build Jest Chance # This should be temporary until there's an official fix for Jest Chance
      run: yarn gulp buildJestChance
    - name: Run unit tests
      run: yarn test:ci
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
    - name: Install dependencies
      run: yarn
    - name: Run linter
      run: yarn lint
